---
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [--fix]  # <- auto-fix import blocks, etc.
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - "--ignore-missing-imports"
          - "--warn-unused-ignores"
          - "--warn-redundant-casts"
          - "--explicit-package-bases"
          - "--exclude"
          - "(^\\.rsg/|^\\.venv/|^venv/|^env/|/site-packages/)"
          - "main_app.py"
          - "ai_analysis.py"
          - "utils"
