[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","UP","B","C4"]
ignore = ["E203","E266"]  # common with black, if you later adopt it

[tool.ruff.isort]
known-first-party = ["ap3tech_tools","utils"]

[tool.mypy]
python_version = "3.11"
strict = false
warn_unused_ignores = true
warn_redundant_casts = true
disallow_untyped_defs = false
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q --disable-warnings --maxfail=1"
testpaths = ["tests"]
