name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Semver (e.g., 1.0.0). Will prepend 'v' if missing."
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
      artifact_name: ${{ steps.meta.outputs.artifact_name }}
    steps:
      - uses: actions/checkout@v4

      # SINGLE meta step; defines both job outputs
      - name: Set release metadata
        id: meta
        shell: pwsh
        run: |
          if ("${{ github.ref }}" -like "refs/tags/*") {
            $tag = "${{ github.ref_name }}"
          } elseif ("${{ inputs.version }}") {
            $v = "${{ inputs.version }}"
            if ($v.StartsWith("v")) { $tag = $v } else { $tag = "v$($v)" }
          } else {
            $tag = "build-${{ github.sha }}".Substring(0, 13)
          }
          "tag=$tag" >> $env:GITHUB_OUTPUT
          "artifact_name=RSG-Recovery-Tools-$tag-Windows.zip" >> $env:GITHUB_OUTPUT
          Write-Host "Tag: $tag"
          Write-Host "Artifact: RSG-Recovery-Tools-$tag-Windows.zip"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller python-dotenv pytest

      - name: Run tests
        run: python -m pytest -q

      - name: Build app (PyInstaller)
        shell: pwsh
        run: |
          pyinstaller main_app.spec --noconfirm --clean `
            --distpath dist `
            --workpath build\pyi_build

      - name: Show dist contents (debug)
        shell: pwsh
        run: |
          if (Test-Path dist) { Get-ChildItem -Recurse dist | Format-Table -AutoSize } else { throw "dist not found" }

      # Zips either a folder (onedir) or a single .exe (onefile)
      - name: Zip artifact (folder or single exe)
        shell: pwsh
        run: |
          $ZipName = "${{ steps.meta.outputs.artifact_name }}"
          $dir = Get-ChildItem dist -Directory | Select-Object -First 1
          if ($dir) {
            Write-Host "Found onedir build: $($dir.Name)"
            Compress-Archive -Path ("dist/{0}/*" -f $dir.Name) -DestinationPath ("dist/{0}" -f $ZipName) -Force
          } else {
            $exe = Get-ChildItem dist -Filter "*.exe" | Select-Object -First 1
            if (-not $exe) { throw "No .exe or app folder found under dist/" }
            Write-Host "Found onefile build: $($exe.Name)"
            Compress-Archive -Path $exe.FullName -DestinationPath ("dist/{0}" -f $ZipName) -Force
          }

      - name: Upload build artifact (CI record)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.meta.outputs.artifact_name }}
          path: dist/${{ steps.meta.outputs.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: ./release_assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.tag }}
          name: RSG Recovery Tools ${{ needs.build.outputs.tag }}
          generate_release_notes: true
          files: |
            release_assets/${{ needs.build.outputs.artifact_name }}
