name: tests-ocr
on:
  push:
    branches: [ pre-prod, main ]
  pull_request:
    branches: [ pre-prod ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Tesseract
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y tesseract-ocr tesseract-ocr-eng
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install tesseract
          else
            choco install tesseract -y
          fi
      - name: Install dev deps
        run: pip install -r requirements-dev.txt

      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Verify Tesseract available (smoke)
        shell: bash
        run: |
          tesseract --version

      - name: Run tests
        run: pytest -q
